---
- name: show version and interfaces
  hosts: R4,R5
  gather_facts: false
  connection: local
  tasks:
    - name: command list
      ios_command:
        commands:
        - show version
        - show ip interface brief
        - show crypto isakmp policy
        - show crypto isakmp peers
        - show crypto isakmp sa
        - show crypto session
        - show crypto map
        - show crypto ipsec sa
        - show crypto engine configuration
        - show crypto ipsec sa | inc encr|decr
      register: print_output
    - debug: var=print_output.stdout_lines
